[package]
name = "clob-binance"
edition.workspace = true
version.workspace = true

[dependencies]
clob-core.workspace = true
clob-venue.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
arrayvec.workspace = true
rustls.workspace = true
uuid.workspace = true
reqwest.workspace = true
async-trait = "0.1"
tracing-subscriber.workspace = true
clap.workspace = true
metrics.workspace = true
hdrhistogram = "7"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "parse"
harness = false
